/*
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"os"
	"time"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"

	"github.com/free5gc/nrf/logger"
	nrf_service "github.com/free5gc/nrf/service"
	"github.com/free5gc/version"
	"github.com/go-redis/redis"
)

var NRF = &nrf_service.NRF{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
        time1 := time.Now().UnixNano() / 1e3
	fmt.Println("golang connecting redis \n")
	client := redis.NewClient(&redis.Options{
        	Addr: "127.0.0.1:6379",
//        	Password: "123456",
		DB: 0,
	})
	pong, err := client.Ping().Result()
	fmt.Println(pong, err)

        err = client.Set("golang",time1, 0).Err()
        if err != nil {
            fmt.Println(err)
        }
//        fmt.Println("time flag set successfully \n")

         val, err := client.Get("golang").Result()
        if err != nil {
          fmt.Println(err)
        }

       fmt.Println("NRF start loading config time is ",val)


	app := cli.NewApp()
	app.Name = "nrf"
	fmt.Print(app.Name, "\n")
	appLog.Infoln("NRF version: ", version.GetVersion())
	app.Usage = "-free5gccfg common configuration file -nrfcfg nrf configuration file"
	app.Action = action
	app.Flags = NRF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		appLog.Errorf("NRF Run Error: %v", err)
	}
}

func action(c *cli.Context) error {
	if err := NRF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("Failed to initialize !!")
	}

	NRF.Start()

	return nil
}
